#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use Symfony\Component\Console\CommandLoader\ContainerCommandLoader;

$container = require __DIR__ . "/bootstrap.php";

$console = new Application(
	\config("app.name"),
	\config("app.version")
);

$console->setCatchExceptions(true);
$console->setCommandLoader(
	new ContainerCommandLoader(
		$container,
		\config("app.commands") ?? []
	)
);

$console->run();