<?php

return [

	/**
	 * Name of the application/service.
	 */
	"name" => "LibraryService",

	/**
	 * Current running environment.
	 */
	"env" => \getenv("ENV"),

	/**
	 * Base timezone.
	 *
	 * All dates and timestamps generated by the application will be in this timezone
	 * including when persisting data to a database.
	 */
	"timezone" => \getenv("TIMEZONE") ?: "UTC",

	/**
	 * Application version.
	 */
	"version" => \file_exists(APP_ROOT . "/VERSION")
			? \trim(\file_get_contents(APP_ROOT . "/VERSION"))
			: \getenv("ENV"),

	/**
	 * Enable/disable debug.
	 *
	 * Enabling this will return detailed information in error responses like
	 * file name, line number, and full stack trace.
	 */
	"debug" => \getenv("DEBUG") === "true",

	/**
	 * Enable/disable logging.
	 *
	 * Enabling this will add stdout logging.
	 */
	"logging" => \getenv("LOGGING") === "true",

	/**
	 * Global application providers.
	 *
	 * Component specific providers (http, queue consumer, and scheduler) are registered
	 * separately.
	 */
	"providers" => [
		App\Providers\LoggerProvider::class,
		App\Providers\DatabaseProvider::class,
		App\Providers\MigrationsProvider::class,
		App\Providers\CommandProvider::class,
		App\Providers\HttpClientProvider::class
	],

	/**
	 * Registered CLI commands.
	 */
	"commands" => [
		"shell" => App\Commands\Shell::class,
		"migrate" => App\Commands\Migrate::class
	]
];